INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('What does AWS stand for?', 'Amazon Web Services', 'Amazon World Solutions', 'Advanced Web Services', 'None of the above', 'A'),
('Which AWS service is used for object storage?', 'Amazon S3', 'Amazon EC2', 'Amazon RDS', 'Amazon VPC', 'A'),
('Which of the following is a serverless compute service?', 'Amazon S3', 'AWS Lambda', 'Amazon EC2', 'Amazon RDS', 'B'),
('What is the default storage type for an Amazon RDS database?', 'Magnetic', 'SSD', 'EBS', 'S3', 'C'),
('Which AWS service is a managed database solution?', 'Amazon EC2', 'Amazon RDS', 'Amazon S3', 'Amazon IAM', 'B'),
('Which service can automatically scale EC2 instances?', 'Elastic Load Balancer', 'Amazon CloudWatch', 'Amazon Auto Scaling', 'Amazon RDS', 'C'),
('Which of the following services is used for data analytics?', 'Amazon Redshift', 'Amazon EC2', 'Amazon VPC', 'Amazon IAM', 'A'),
('Which AWS service provides content delivery?', 'Amazon RDS', 'Amazon CloudFront', 'Amazon EC2', 'Amazon VPC', 'B'),
('Which AWS service is used for orchestration of containerized applications?', 'Amazon S3', 'Amazon ECS', 'Amazon RDS', 'Amazon Redshift', 'B'),
('Which of the following is not a database service on AWS?', 'Amazon DynamoDB', 'Amazon S3', 'Amazon RDS', 'Amazon Redshift', 'B'),
('Which service allows you to run code without provisioning or managing servers?', 'Amazon EC2', 'Amazon RDS', 'AWS Lambda', 'Amazon S3', 'C'),
('What is the primary storage service used by Amazon EC2?', 'Amazon S3', 'EBS', 'RDS', 'CloudFront', 'B'),
('Which service is designed for secure, durable, and scalable storage of backups?', 'Amazon EC2', 'Amazon S3', 'Amazon CloudWatch', 'Amazon Redshift', 'B'),
('Which AWS service allows you to register and manage domains?', 'Amazon RDS', 'Amazon Route 53', 'Amazon CloudFront', 'Amazon VPC', 'B'),
('Which AWS service helps in monitoring and managing the health of AWS resources?', 'Amazon S3', 'Amazon Route 53', 'Amazon CloudWatch', 'Amazon EC2', 'C'),
('Which service is used to run SQL queries on S3 data?', 'Amazon Athena', 'Amazon RDS', 'Amazon DynamoDB', 'Amazon Redshift', 'A'),
('Which service helps in managing and deploying AWS infrastructure as code?', 'Amazon EC2', 'AWS CloudFormation', 'Amazon RDS', 'Amazon S3', 'B'),
('Which AWS service is used to run containerized applications?', 'Amazon S3', 'Amazon RDS', 'Amazon ECS', 'Amazon VPC', 'C'),
('Which of the following is a key-value database?', 'Amazon RDS', 'Amazon Redshift', 'Amazon DynamoDB', 'Amazon S3', 'C'),
('Which service is used for messaging and queuing?', 'Amazon S3', 'Amazon EC2', 'Amazon SQS', 'Amazon RDS', 'C');